---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloud-dex
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: k8s-platform
  syncPolicy:
    automated:
      prune: true
  destination:
    name: cloud
    namespace: dex
  source:
    repoURL: https://charts.dexidp.io
    targetRevision: 0.24.0
    chart: dex
    helm:
      releaseName: dex
      values: |

        replicaCount: 3
        volumes:
          - name: tmp
            emptyDir: {}
        volumeMounts:
          - mountPath: /tmp
            name: tmp
        envVars:
          - name: MICROSOFT_APPLICATION_ID
            valueFrom:
              secretKeyRef:
                name: dex-secrets
                key: microsoft-application-id
          - name: MICROSOFT_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: dex-secrets
                key: microsoft-client-secret
          - name: MICROSOFT_TENANT_ID
            valueFrom:
              secretKeyRef:
                name: dex-secrets
                key: microsoft-tenant-id
          - name: KUBELOGIN_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: dex-secrets
                key: kubelogin-client-secret
          - name: ARGO_WORKFLOWS_SSO_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: dex-secrets
                key: argo-workflows-sso-client-secret
        config:
          issuer: https://auth.derwitt.dev
          storage:
            type: kubernetes
            config:
              inCluster: true
          staticClients:
            - id: kubelogin
              name: "Kubernetes"
              redirectURIs:
                - "http://localhost:8000"
                - "http://localhost:18000"
              secretEnv: KUBELOGIN_CLIENT_SECRET
            - id: argo-workflows
              name: Argo Workflows
              redirectURIs:
                - https://workflows.derwitt.dev/oauth2/callback
              secretEnv: ARGO_WORKFLOWS_SSO_CLIENT_SECRET
          connectors:
            - type: microsoft
              id: microsoft
              name: Microsoft
              config:
                clientID: "{{ .Env.MICROSOFT_APPLICATION_ID }}"
                clientSecret: "{{ .Env.MICROSOFT_CLIENT_SECRET }}"
                redirectURI: https://auth.derwitt.dev/callback
                tenant: "{{ .Env.MICROSOFT_TENANT_ID }}"
                emailToLowercase: true
                onlySecurityGroups: true
                useGroupsAsWhitelist: true
                groups:
                  - k8s-readers
                  - k8s-admins
        securityContext:
          capabilities:
            drop:
              - ALL
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1000
        podSecurityContext:
          runAsUser: 1000
          runAsGroup: 1000
          seccompProfile:
            type: RuntimeDefault
        resources:
          requests:
            cpu: 10m
            memory: 104Mi
          limits:
            memory: 104Mi
        serviceMonitor:
          enabled: true
        networkPolicy:
          enabled: true
        ingress:
          enabled: true
          className: traefik
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt
            traefik.ingress.kubernetes.io/router.middlewares: "traefik-redirect-to-https@kubernetescrd"
          hosts:
            - host: auth.derwitt.dev
              paths:
                - path: /
                  pathType: ImplementationSpecific
          tls:
            - hosts:
                - auth.derwitt.dev
              secretName: dex-ingress-cert
