---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloud-hcloud-cloud-controller-manager
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: k8s-platform
  syncPolicy:
    automated:
      prune: true
  destination:
    name: cloud
    namespace: kube-system
  source:
    repoURL: https://charts.hetzner.cloud
    targetRevision: 1.30.1
    chart: hcloud-cloud-controller-manager
    helm:
      releaseName: hccm
      valuesObject:
        networking:
          enabled: true
          clusterCIDR: 10.128.0.0/16
        monitoring:
          enabled: true
          podMonitor:
            enabled: true
