---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloud-loki
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: k8s-platform
  syncPolicy:
    automated:
      prune: true
  destination:
    name: cloud
    namespace: loki
  source:
    repoURL: oci://ghcr.io/grafana-community/helm-charts/loki
    path: .
    targetRevision: 13.3.1
    helm:
      releaseName: loki
      valuesObject:
        global:
          dnsService: "kube-dns"
          dnsNamespace: "kube-system"
        loki:
          auth_enabled: false
          podSecurityContext:
            fsGroup: 10001
            fsGroupChangePolicy: OnRootMismatch
            runAsGroup: 10001
            runAsNonRoot: true
            runAsUser: 10001
            seccompProfile:
              type: RuntimeDefault
          schemaConfig:
            configs:
              - from: 2024-04-01
                store: tsdb
                object_store: s3
                schema: v13
                index:
                  prefix: loki_index_
                  period: 24h
          ingester:
            chunk_encoding: snappy
          tracing:
            enabled: true
          querier:
            max_concurrent: 4
          rulerConfig:
            external_url: https://graphs.derwitt.dev
            alertmanager_url: https://alerts.derwitt.dev
            enable_alertmanager_v2: true
            remote_write:
              enabled: true
              clients:
                vmsingle:
                  url: http://vmsingle-vm-stack-victoria-metrics-k8s-stack.victoria-metrics-stack.svc.cluster.local:8429/api/v1/write
          compactor:
            retention_enabled: true
            compaction_interval: 10m
            retention_delete_delay: 2h
            retention_delete_worker_count: 50
            delete_request_store: s3
          limits_config:
            retention_period: 168h # 1 week
            per_tenant_override_config: /etc/overrides.yaml
          storage:
            type: s3
            bucketNames:
              chunks: "loki-chunks"
              ruler: "loki-ruler"
              admin: "loki-admin"
            s3:
              endpoint: http://cloud-garage-default-headless.storage.svc.cluster.local:3900
              region: cloud
              insecure: true
              accessKeyId: ${S3_ACCESS_KEY}
              secretAccessKey: ${S3_SECRET_KEY}
              s3ForcePathStyle: true

        lokiCanary:
          resources:
            requests:
              cpu: 10m
              memory: 100Mi
            limits:
              memory: 100Mi

        gateway:
          podSecurityContext:
            fsGroup: 101
            fsGroupChangePolicy: OnRootMismatch
            runAsGroup: 101
            runAsNonRoot: true
            runAsUser: 101
            seccompProfile:
              type: RuntimeDefault
          resources:
            requests:
              cpu: 10m
              memory: 100Mi
            limits:
              memory: 100Mi

        chunksCache:
          allocatedMemory: 1024
          resources:
            requests:
              cpu: 10m
              memory: 1229Mi # should be allocatedMemory * 1.2
            limits:
              memory: 1229Mi

        resultsCache:
          allocatedMemory: 1024
          resources:
            requests:
              cpu: 10m
              memory: 1229Mi # should be allocatedMemory * 1.2
            limits:
              memory: 1229Mi

        deploymentMode: SimpleScalable
        backend:
          replicas: 2
          persistence:
            size: 1Gi
            storageClass: longhorn
          extraArgs:
            - -config.expand-env=true
            - -log.level=warn
            - -log.format=json
          extraVolumes:
            - name: cluster-ca-cert
              secret:
                defaultMode: 420
                secretName: cluster-ca-secret
          extraVolumeMounts:
            - mountPath: /config/certs
              name: cluster-ca-cert
              readOnly: true
          extraEnv:
            - name: S3_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  key: access-key
                  name: s3-settings
            - name: S3_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  key: secret-key
                  name: s3-settings
        read:
          replicas: 3
          extraArgs:
            - -config.expand-env=true
            - -log.level=warn
            - -log.format=json
          extraVolumes:
            - name: cluster-ca-cert
              secret:
                defaultMode: 420
                secretName: cluster-ca-secret
          extraVolumeMounts:
            - mountPath: /config/certs
              name: cluster-ca-cert
              readOnly: true
          extraEnv:
            - name: S3_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  key: access-key
                  name: s3-settings
            - name: S3_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  key: secret-key
                  name: s3-settings
          resources:
            requests:
              cpu: 21m
              memory: 296Mi
            limits:
              memory: 296Mi
        write:
          replicas: 2
          persistence:
            size: 1Gi
            storageClass: longhorn
          extraArgs:
            - -config.expand-env=true
            - -log.level=warn
            - -log.format=json
          extraVolumes:
            - name: cluster-ca-cert
              secret:
                defaultMode: 420
                secretName: cluster-ca-secret
          extraVolumeMounts:
            - mountPath: /config/certs
              name: cluster-ca-cert
              readOnly: true
          extraEnv:
            - name: S3_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  key: access-key
                  name: s3-settings
            - name: S3_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  key: secret-key
                  name: s3-settings
          resources:
            requests:
              cpu: 28m
              memory: 306Mi
            limits:
              memory: 306Mi

        # other deployment modes scaled to zero
        singleBinary:
          replicas: 0
        ingester:
          replicas: 0
        querier:
          replicas: 0
        queryFrontend:
          replicas: 0
        queryScheduler:
          replicas: 0
        distributor:
          replicas: 0
        compactor:
          replicas: 0
        indexGateway:
          replicas: 0
        bloomCompactor:
          replicas: 0
        bloomGateway:
          replicas: 0
