---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloud-oauth2-proxy-resources
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: k8s-platform
  syncPolicy:
    automated:
      prune: true
  destination:
    name: cloud
    namespace: oauth2-proxy
  source:
    repoURL: https://github.com/wittdennis/k8s-platform
    targetRevision: HEAD
    path: "cloud/oauth2-proxy"
    directory:
      recurse: true
