---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloud-victoria-metrics-stack-resources
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: k8s-platform
  syncPolicy:
    automated:
      prune: true
  destination:
    name: cloud
    namespace: victoria-metrics-stack
  source:
    repoURL: https://git.derwitt.site/homelab/yggdrasil
    targetRevision: HEAD
    path: "cloud/victoria-metrics-stack"
    directory:
      recurse: true
