---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloud-yas3p
  namespace: argocd
spec:
  project: k8s-platform
  destination:
    name: cloud
    namespace: storage
  syncPolicy:
    automated:
      prune: true
  source:
    repoURL: https://charts.derwitt.dev
    targetRevision: 0.3.1
    chart: yas3p
    helm:
      releaseName: yas3p
      values: |

        yas3p:
          endpoint: s3.derwitt.dev
          region: cloud
          buckets:
            - name: foundry-caq
              accessKeyIdEnv: foundry-caq-r-access-key-id
              secretKeyEnv: foundry-caq-r-secret-key
            - name: foundry-saltysausage
              accessKeyIdEnv: foundry-saltysausage-access-key
              secretKeyEnv: foundry-saltysausage-secret-key
        replicaCount: 2
        env:
          - name: TZ
            value: Europe/Berlin
          - name: foundry-caq-r-access-key-id
            valueFrom:
              secretKeyRef:
                name: foundry-caq-read-key
                key: access-key-id
          - name: foundry-caq-r-secret-key
            valueFrom:
              secretKeyRef:
                name: foundry-caq-read-key
                key: secret-key
          - name: foundry-saltysausage-access-key
            valueFrom:
              secretKeyRef:
                name: foundry-saltysausage-access-key
                key: access-key
          - name: foundry-saltysausage-secret-key
            valueFrom:
              secretKeyRef:
                name: foundry-saltysausage-access-key
                key: secret-key
        ingress:
          enabled: true
          className: traefik
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt
            traefik.ingress.kubernetes.io/router.middlewares: "traefik-redirect-to-https@kubernetescrd"
          hosts:
            - host: s3-pub.derwitt.dev
              paths:
                - path: /
                  pathType: ImplementationSpecific
            - host: "*.s3-pub.derwitt.dev"
              paths:
                - path: /
                  pathType: ImplementationSpecific
          tls:
            - secretName: yas3p-ingress-tls
              hosts:
                - s3-pub.derwitt.dev
                - "*.s3-pub.derwitt.dev"
