---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: paperless-ngx-postgres
spec:
  instances: 2
  logLevel: warning
  enablePDB: false
  primaryUpdateStrategy: unsupervised
  enableSuperuserAccess: false
  bootstrap:
    initdb:
      database: paperless
      owner: paperless
  imageCatalogRef:
    apiGroup: postgresql.cnpg.io
    kind: ClusterImageCatalog
    name: postgres
    major: 18
  managed:
    roles:
      - name: paperless
        superuser: false
        createdb: false
        login: true
  postgresql:
    shared_preload_libraries:
      - pg_partman_bgw
  monitoring:
    enablePodMonitor: true
  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: backup-store
  resources:
    requests:
      cpu: 100m
      ephemeral-storage: 50Mi
      memory: 128Mi
  storage:
    size: 15Gi
    storageClass: proxmox-data
  walStorage:
    size: 5Gi
    storageClass: proxmox-data
