---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: radicale-auth-htpasswd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend-platform
    kind: ClusterSecretStore
  target:
    name: radicale-auth-htpasswd
    creationPolicy: Owner
    deletionPolicy: Delete
  data:
    - remoteRef:
        conversionStrategy: Default
        key: /radicale/auth
        property: htpasswd
      secretKey: htpasswd
