---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: litellm-masterkey
spec:
  refreshInterval: "1h0m0s"
  secretStoreRef:
    name: vault-backend-platform
    kind: ClusterSecretStore
  target:
    name: litellm-masterkey
    creationPolicy: Owner
    deletionPolicy: Delete
  data:
    - remoteRef:
        conversionStrategy: Default
        key: /ai-platform/litellm/master-key
        property: key
      secretKey: masterkey
