---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: open-webui-secrets
spec:
  refreshInterval: "1h0m0s"
  secretStoreRef:
    name: vault-backend-platform
    kind: ClusterSecretStore
  target:
    name: open-webui-secrets
    creationPolicy: Owner
    deletionPolicy: Delete
  data:
    - remoteRef:
        conversionStrategy: Default
        key: authentik/oauth2-clients/open-webui
        property: client-secret
      secretKey: OAUTH_CLIENT_SECRET
    - remoteRef:
        conversionStrategy: Default
        key: /ai-platform/open-webui/litellm-key
        property: key
      secretKey: OPENAI_API_KEY
    - remoteRef:
        conversionStrategy: Default
        key: /ai-platform/open-webui/secret-key
        property: key
      secretKey: WEBUI_SECRET_KEY
