---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: turnstone-allow-postgres-egress
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: turnstone
      app.kubernetes.io/instance: turnstone
  egress:
    - toEndpoints:
        - matchLabels:
            cnpg.io/cluster: turnstone-postgres
      toPorts:
        - ports:
            - port: "5432"
              protocol: TCP
