---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: vault-backend-home-assistant
spec:
  provider:
    vault:
      server: "https://vault.derwitt.site"
      path: "home-assistant"
      version: "v2"
      auth:
        tokenSecretRef:
          name: "vault-home-assistant-path-token"
          namespace: external-secrets
          key: "token"
