---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: vault-backend-platform
spec:
  provider:
    vault:
      server: "https://vault.derwitt.site"
      path: "platform"
      version: "v2"
      auth:
        tokenSecretRef:
          name: "vault-platform-path-token"
          namespace: external-secrets
          key: "token"
