---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-oidc-credentials
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend-platform
    kind: ClusterSecretStore
  target:
    name: grafana-oidc-credentials
    creationPolicy: Owner
  data:
    - remoteRef:
        conversionStrategy: Default
        key: /victoria-metrics-stack/grafana/oidc-creds
        property: azure-application-id
      secretKey: GF_AUTH_AZUREAD_CLIENT_ID
    - remoteRef:
        conversionStrategy: Default
        key: /victoria-metrics-stack/grafana/oidc-creds
        property: azure-client-secret
      secretKey: GF_AUTH_AZUREAD_CLIENT_SECRET
