---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-oidc-credentials
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend-homelab-platform
    kind: ClusterSecretStore
  target:
    name: grafana-oidc-credentials
    creationPolicy: Owner
  data:
    - remoteRef:
        conversionStrategy: Default
        key: authentik/oauth2-clients/grafana
        property: client-secret
      secretKey: GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET
