---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mogenius-operator-ai-settings
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend-platform
    kind: ClusterSecretStore
  target:
    name: mogenius-operator-ai-settings
    creationPolicy: Owner
    deletionPolicy: Delete
  data:
    - remoteRef:
        conversionStrategy: Default
        key: /mogenius-operator-dev/ai-settings
        property: api-key
      secretKey: api-key
