---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: garage-rpc
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend-platform
    kind: ClusterSecretStore
  target:
    name: garage-rpc
    creationPolicy: Owner
    deletionPolicy: Delete
  data:
    - remoteRef:
        conversionStrategy: Default
        key: /storage/garage
        property: rpc-secret
      secretKey: rpcSecret
