---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-backups-backup-settings
spec:
  refreshInterval: "1h0m0s"
  secretStoreRef:
    name: vault-backend-platform
    kind: ClusterSecretStore
  target:
    name: postgres-backups-backup-settings
    creationPolicy: Owner
    deletionPolicy: Delete
  data:
    - remoteRef:
        conversionStrategy: Default
        key: storage/postgres-backups-restic-password
        property: restic-password
      secretKey: restic-password
    - remoteRef:
        conversionStrategy: Default
        key: shared/hetzner-backup-bucket-credentials
        property: access-key
      secretKey: access-key
    - remoteRef:
        conversionStrategy: Default
        key: shared/hetzner-backup-bucket-credentials
        property: secret-key
      secretKey: secret-key
