---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-backups-read-credentials
spec:
  refreshInterval: "1h0m0s"
  secretStoreRef:
    name: vault-backend-platform
    kind: ClusterSecretStore
  target:
    name: postgres-backups-read-credentials
    creationPolicy: Owner
    deletionPolicy: Delete
  data:
    - remoteRef:
        conversionStrategy: Default
        key: storage/postgres-backups-read-credentials
        property: access-key
      secretKey: access-key
    - remoteRef:
        conversionStrategy: Default
        key: storage/postgres-backups-read-credentials
        property: secret-key
      secretKey: secret-key
