---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: chartmuseum-secrets
spec:
  refreshInterval: "1h"
  target:
    name: chartmuseum-secrets
    creationPolicy: Owner
    deletionPolicy: Delete
  secretStoreRef:
    name: vault-backend-platform
    kind: ClusterSecretStore
  data:
    - remoteRef:
        conversionStrategy: Default
        key: /chartmuseum/azure-storage-account
        property: account-key
      secretKey: azure-storage-access-key
    - remoteRef:
        conversionStrategy: Default
        key: /chartmuseum/azure-storage-account
        property: account-name
      secretKey: azure-storage-account
    - remoteRef:
        conversionStrategy: Default
        key: /chartmuseum/basic-auth
        property: user
      secretKey: basic-auth-user
    - remoteRef:
        conversionStrategy: Default
        key: /chartmuseum/basic-auth
        property: password
      secretKey: basic-auth-pass
    - remoteRef:
        conversionStrategy: Default
        key: /chartmuseum/artifacthub
        property: repo-id
      secretKey: artifacthub-repo-id
