---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: authentik-db-backup
spec:
  schedule: "0 0 0 * * *" # At midnight every day
  backupOwnerReference: self
  cluster:
    name: authentik-postgres
  method: plugin
  target: prefer-standby
  immediate: true
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
