---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: radicale-workflows-scaler-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: workload-scaler
subjects:
  - kind: ServiceAccount
    name: radicale-workflows
