---
name: lint

permissions: {}

on:
  pull_request:
    branches:
      - main
      - release/**

jobs:
  lint:
    runs-on: debian-12
    permissions:
      contents: read
    steps:
      - uses: https://git.derwitt.site/actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: setup uv
        uses: https://git.derwitt.site/actions/setup-uv@cec208311dfd045dd5311c1add060b2062131d57 # v8.0.0

      - name: install yamllint
        run: |
          uv tool install yamllint@${YAMLLINT_VERSION}
          uv tool list
        env:
          YAMLLINT_VERSION: 1.38.0 # datasource=pypi depName=yamllint packageName=yamllint versioning=semver

      - name: lint
        run: |
          yamllint -c .yamllint .
