---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: home-assistant-external-secrets
  namespace: argocd
spec:
  project: k8s-platform
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
    automated:
      prune: true
  destination:
    name: home-assistant
    namespace: external-secrets
  source:
    repoURL: https://charts.external-secrets.io
    targetRevision: 2.10.0
    chart: external-secrets
    helm:
      releaseName: external-secrets
      values: |

        podSecurityContext:
          runAsUser: 1000
          runAsGroup: 1000
          seccompProfile:
            type: RuntimeDefault
        serviceMonitor:
          enabled: true
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
          limits:
            memory: 100Mi
        webhook:
          podSecurityContext:
            runAsUser: 1000
            runAsGroup: 1000
            seccompProfile:
              type: RuntimeDefault
          resources:
            requests:
              cpu: 10m
              memory: 100Mi
            limits:
              memory: 100Mi
        certController:
          podSecurityContext:
            runAsUser: 1000
            runAsGroup: 1000
            seccompProfile:
              type: RuntimeDefault
          resources:
            requests:
              cpu: 10m
              memory: 100Mi
            limits:
              memory: 100Mi
