---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: home-assistant-traefik-resources
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: k8s-platform
  syncPolicy:
    automated:
      prune: true
  destination:
    name: home-assistant
    namespace: traefik
  source:
    repoURL: https://github.com/wittdennis/k8s-platform
    targetRevision: HEAD
    path: "home-assistant/traefik"
    directory:
      recurse: true
