---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: alertmanager-pagerduty-routing-key
  namespace: victoria-metrics-stack
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend-platform
    kind: ClusterSecretStore
  target:
    name: pagerduty-routing-key
    creationPolicy: Owner
  data:
    - remoteRef:
        conversionStrategy: Default
        key: /victoria-metrics-stack/alertmanager/pagerduty
        property: routing-key
      secretKey: routing-key
