---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: etcd-client-certificate
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: vault-backend-platform
    kind: ClusterSecretStore
  target:
    name: etcd-client-certificate
    creationPolicy: Owner
  data:
    - remoteRef:
        conversionStrategy: Default
        key: /victoria-metrics-stack/etcd
        property: client.crt
      secretKey: client.crt
    - remoteRef:
        conversionStrategy: Default
        key: /victoria-metrics-stack/etcd
        property: client.key
      secretKey: client.key
