---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-oidc-credentials
  namespace: victoria-metrics-stack
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend-platform
    kind: ClusterSecretStore
  target:
    name: grafana-oidc-credentials
    creationPolicy: Owner
  data:
    - remoteRef:
        conversionStrategy: Default
        key: /grafana
        property: azure-application-id
      secretKey: GF_AUTH_AZUREAD_CLIENT_ID
    - remoteRef:
        conversionStrategy: Default
        key: /grafana
        property: azure-client-secret
      secretKey: GF_AUTH_AZUREAD_CLIENT_SECRET
    - remoteRef:
        conversionStrategy: Default
        key: authentik/oauth2-clients/grafana
        property: client-secret
      secretKey: GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET
