---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: vault-backend-homelab-platform
spec:
  provider:
    vault:
      server: "https://vault-homelab.tailnet.derwitt.net:8200"
      path: "platform"
      version: "v2"
      caProvider:
        type: ConfigMap
        name: homelab-vault-ca
        namespace: external-secrets
        key: ca.crt
      auth:
        tokenSecretRef:
          name: "vault-homelab-platform-token"
          namespace: external-secrets
          key: "token"
