---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: vault-backend-platform
spec:
  provider:
    vault:
      server: "https://vault.hashicorp-vault.svc.cluster.local:8200"
      path: "platform"
      version: "v2"
      caProvider:
        type: Secret
        name: vault-server-cert
        namespace: hashicorp-vault
        key: ca.crt
      auth:
        tokenSecretRef:
          name: "vault-platform-path-token"
          namespace: external-secrets
          key: "token"
