---
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: radicale-uptime
spec:
  jobName: radicale-uptime
  interval: 1m
  module: http_2xx
  prober:
    url: prometheus-blackbox-exporter.prometheus-blackbox-exporter.svc.cluster.local:9115
  targets:
    staticConfig:
      static:
        - https://calendar.derwitt.site
      labels:
        group: backup-targets
