---
apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
  name: argo-workflows-secret
spec:
  namespaceSelector:
    matchLabels:
      argo-workflows: "true"
  externalSecretSpec:
    refreshInterval: 1h
    secretStoreRef:
      name: vault-backend-platform
      kind: ClusterSecretStore
    target:
      name: argo-workflows
      creationPolicy: Owner
      deletionPolicy: Delete
    data:
      - remoteRef:
          conversionStrategy: Default
          decodingStrategy: None
          key: /storage/workflows-credentials
          property: access-key
          metadataPolicy: None
          nullBytePolicy: Ignore
        secretKey: access-key
      - remoteRef:
          conversionStrategy: Default
          decodingStrategy: None
          key: /storage/workflows-credentials
          property: secret-key
          metadataPolicy: None
          nullBytePolicy: Ignore
        secretKey: secret-key
