---
apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
  name: postgres-backups-credentials
spec:
  namespaceSelector:
    matchLabels:
      postgres-backup: "true"
  externalSecretSpec:
    refreshInterval: "1h0m0s"
    secretStoreRef:
      name: vault-backend-platform
      kind: ClusterSecretStore
    target:
      name: postgres-backups-credentials
      creationPolicy: Owner
      deletionPolicy: Delete
    data:
      - remoteRef:
          conversionStrategy: Default
          decodingStrategy: None
          key: /storage/postgres-backups-credentials
          property: access-key
          metadataPolicy: None
          nullBytePolicy: Ignore
        secretKey: access-key
      - remoteRef:
          conversionStrategy: Default
          decodingStrategy: None
          key: /storage/postgres-backups-credentials
          property: secret-key
          metadataPolicy: None
          nullBytePolicy: Ignore
        secretKey: secret-key
      - remoteRef:
          conversionStrategy: Default
          decodingStrategy: None
          key: /storage/postgres-backups-credentials
          property: region
          metadataPolicy: None
          nullBytePolicy: Ignore
        secretKey: region
