---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: email-settings
spec:
  refreshInterval: "1h0m0s"
  secretStoreRef:
    name: vault-backend-platform
    kind: ClusterSecretStore
  target:
    name: email-settings
    creationPolicy: Owner
    deletionPolicy: Delete
  data:
    - remoteRef:
        conversionStrategy: Default
        key: /paperless-ngx/email
        property: password
      secretKey: password
