---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: paperless-ngx-litellm-key
spec:
  refreshInterval: "1h0m0s"
  secretStoreRef:
    name: vault-backend-platform
    kind: ClusterSecretStore
  target:
    name: paperless-ngx-litellm-key
    creationPolicy: Owner
    deletionPolicy: Delete
  data:
    - remoteRef:
        conversionStrategy: Default
        key: /paperless-ngx/ai
        property: api-token
      secretKey: api-token
