---
apiVersion: gateway.networking.k8s.io/v1
kind: BackendTLSPolicy
metadata:
  name: tls-vault-upstream-auth
spec:
  targetRefs:
    - group: ""
      kind: Service
      name: vault-active
      sectionName: https
  validation:
    caCertificateRefs:
      - kind: ConfigMap
        name: cluster-ca
        group: ""
    hostname: vault.hashicorp-vault.svc.cluster.local
