---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: renovate-operator-api
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    traefik.ingress.kubernetes.io/router.middlewares: "traefik-redirect-to-https@kubernetescrd"
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - api.renovate.derwitt.dev
      secretName: renovate-operator-api-ingress-tls
  rules:
    - host: api.renovate.derwitt.dev
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: renovate-operator-api-homelab
                port:
                  number: 443
