---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: renovate-webhook-token
  labels:
    renovate-operator.mogenius.com/allow-ref: "true"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend-platform
    kind: ClusterSecretStore
  target:
    name: renovate-webhook-token
    creationPolicy: Owner
    deletionPolicy: Delete
  data:
    - remoteRef:
        conversionStrategy: Default
        key: /renovate-operator/webhook-config
        property: token
      secretKey: token
    - remoteRef:
        conversionStrategy: Default
        key: /renovate-operator/webhook-config
        property: forgejo-sync-token
      secretKey: forgejo-api-token
