---
apiVersion: kyverno.io/v1
kind: Policy
metadata:
  name: mutate-redis-exporter-password
  annotations:
    policies.kyverno.io/title: Modify valkey pod redis-exporter environment variables
    policies.kyverno.io/category: Mutation
    policies.kyverno.io/subject: Pod
spec:
  admission: true
  background: false
  rules:
    - match:
        resources:
          kinds:
            - Pod
          names:
            - netbox-valkey-*
      name: modify-redis-exporter-environment
      skipBackgroundRequests: true
      mutate:
        patchStrategicMerge:
          spec:
            containers:
              - (name): "metrics"
                env:
                  - name: REDIS_PASSWORD
                    valueFrom:
                      secretKeyRef:
                        name: netbox-valkey-credentials
                        key: default-password
