---
apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
data:
  Corefile: |
    .:53 {
        errors
        health {
           lameduck 5s
        }
        ready
        kubernetes cluster.local in-addr.arpa ip6.arpa {
           pods insecure
           fallthrough in-addr.arpa ip6.arpa
           ttl 30
        }
        prometheus :9153
        forward . /etc/resolv.conf {
           max_concurrent 1000
        }
        cache 30 {
           disable success cluster.local
           disable denial cluster.local
        }
        loop
        reload
        loadbalance
    }
    tailnet.derwitt.net:53 {
        errors
        cache 30
        forward . 100.100.100.100 fd7a:115c:a1e0::53
    }
