---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homelab-atlantis-resources
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: k8s-platform
  syncPolicy:
    automated:
      prune: true
  destination:
    name: homelab
    namespace: atlantis
  source:
    repoURL: https://github.com/wittdennis/k8s-platform
    targetRevision: HEAD
    path: "homelab/atlantis"
    directory:
      recurse: true
