---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homelab-gateway-api-crds
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: homelab
    namespace: kube-system
  project: k8s-platform
  syncPolicy:
    automated:
      enabled: true
    syncOptions:
      - ServerSideApply=true
      - ApplyOutOfSyncOnly=true
  source:
    repoURL: https://github.com/kubernetes-sigs/gateway-api
    targetRevision: v1.5.1
    path: config/crd/experimental
