---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homelab-mogenius-operator-dev-resources
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: k8s-platform
  syncPolicy:
    automated:
      prune: true
  destination:
    name: homelab
    namespace: mogenius-operator-dev
  source:
    repoURL: https://git.derwitt.site/homelab/yggdrasil
    targetRevision: HEAD
    path: "homelab/mogenius-operator-dev"
    directory:
      recurse: true
