---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homelab-prometheus-operator-crds
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: k8s-platform
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - ServerSideApply=true
  destination:
    name: homelab
    namespace: victoria-metrics-stack
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 31.0.0
    chart: prometheus-operator-crds
    helm:
      releaseName: prometheus-operator-crds
