---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homelab-victoria-metrics-operator-resources
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: k8s-platform
  syncPolicy:
    automated:
      prune: true
  destination:
    name: homelab
    namespace: victoria-metrics-operator
  source:
    repoURL: https://git.derwitt.site/homelab/yggdrasil
    targetRevision: HEAD
    path: "homelab/victoria-metrics-operator"
    directory:
      recurse: true
