---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: modify-argo-workflows-crd-install
  annotations:
    policies.kyverno.io/title: Modify Argo Workflows crd install job
    policies.kyverno.io/category: Security
    policies.kyverno.io/subject: Pod
spec:
  rules:
    - name: modify-pod-security
      match:
        any:
          - resources:
              kinds:
                - Pod
              names:
                - argo-workflows-crd-install-*
              operations:
                - CREATE
      mutate:
        patchStrategicMerge:
          spec:
            automountServiceAccountToken: false
            securityContext:
              runAsNonRoot: true
              runAsUser: 1000
              runAsGroup: 1000
              fsGroup: 1000
              seccompProfile:
                type: RuntimeDefault
            containers:
              - name: apply
                securityContext:
                  allowPrivilegeEscalation: false
                  runAsNonRoot: true
                  runAsUser: 1000
                  runAsGroup: 1000
                  capabilities:
                    drop:
                      - ALL
