---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argo-workflows-oidc-secret
  namespace: argo-workflows
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend-platform
    kind: ClusterSecretStore
  target:
    name: argo-workflows-oidc
    creationPolicy: Owner
    deletionPolicy: Delete
  data:
    - remoteRef:
        conversionStrategy: Default
        key: /argo-workflows/oidc-config
        property: client-id
      secretKey: client-id
    - remoteRef:
        conversionStrategy: Default
        key: authentik/oauth2-clients/argo-workflows
        property: client-secret
      secretKey: client-secret
