---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-email-settings
spec:
  refreshInterval: "1h0m0s"
  secretStoreRef:
    name: vault-backend-platform
    kind: ClusterSecretStore
  target:
    name: authentik-email-settings
    creationPolicy: Owner
    deletionPolicy: Delete
  data:
    - remoteRef:
        conversionStrategy: Default
        key: /authentik/configuration
        property: email-password
      secretKey: password
