---
apiVersion: v1
kind: ConfigMap
metadata:
  name: homelab-vault-ca
  namespace: external-secrets
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIE+jCCAuKgAwIBAgIUfnL6lkI7DRwmPzPwAwwO9hkO+YgwDQYJKoZIhvcNAQEN
    BQAwFTETMBEGA1UEAxMKZGVyd2l0dCBDQTAeFw0yNTExMDUxNTAyNDlaFw0zMDEx
    MDQxNTAyNDlaMBUxEzARBgNVBAMTCmRlcndpdHQgQ0EwggIiMA0GCSqGSIb3DQEB
    AQUAA4ICDwAwggIKAoICAQCu8GRzzQQgAP3ssTCCz4t0Z+1p3Ua4Out0djDtvC14
    62xPtxmlnCRe/MLYZl1BDd0c7w4NeWi433KxLq0Snr+f9WIQl22XmvFxBQPZ9kUB
    xVxQxznCyC0dnstbJBi/fVPKFiXoYOkr/ZEijro98rwcLOGySrS8A3tncZ/G2KcH
    IIBQ7zR9bNsuQhiyM99dm8uSyHcxFminVlSl6ch0b0MWbxUyUzUBzsHv2PbY4LyW
    qxWYE7lGooP4LQF1EXuTZtwsgxUrhb7GKrby7HE1AXJ428Nd4q/b0y434zL42vgv
    EpPvD4hpkZvfAP6Ns8z/VwliXbCyTgR91XJM7Ura+qnvOBZX6Ub+/T1+NwDHBe9b
    BYi1GLdKaisboFCthpoBzlUj78YKt+PJWZ8R6aZeQyVSDinXLrjfEb25NXWxQsIL
    +iQVko4Fb/IWu+UqT2SNv+/Os95P6ZqyWmhRlmRSszvoIZME3urKX8G1zNcJ4rrU
    M0zMsBMcXtvDYZ6+vrFDtMxY23q4pZ7/kWN/Q9UZDy/mC9N6MgAPg5tl2i1KuwNT
    I6KbsZBH2YYoaO2/YotWEfItNrSWOLFwgfp/uAMyz8Ml7ycowfvIB8u6ZcBD6YdR
    b1Nm+gz8XTahfBwbhe4E3hMvuyZAnCUOOaCB0wOtPZeeAihjgEQU/DjYI+cbf2sW
    WwIDAQABo0IwQDAOBgNVHQ8BAf8EBAMCAqQwDwYDVR0TAQH/BAUwAwEB/zAdBgNV
    HQ4EFgQUJtdNuknttA4enjIh5B8wTrm98e8wDQYJKoZIhvcNAQENBQADggIBAHf3
    uUJ3JO6OSPJEWpYAASeuyvmTwW9Iiq8J2fevmAu/gCfvhoNKX8z6OoNL2GZQMp9z
    kxCd4sBpVhpECrnXysWIX5ZnaB/21mB4l3acPpu3oJehoUZuJP7+g/624iGuRlGi
    HKBrBWhgsV3Z6ZvrTNOI29JYl89ygI1/UKzU57zxRgn34z1msl/AW3ydM3oCPE8d
    OSmpLF8QiR3KcMmLqbocTRxIkDg89XhcTikXAzP5PbKELA5LS5OJB05UyM9uaKR3
    w+Juh+pau1SI4Q8Qkr3g3s/CgsqNvKc2ZM33HUCXuPzlRpYF2iitv7rJvRVqB3mc
    /ArJD9AMQA6kORxOdzV7a3GdhqUsNNS6Pwypjxpe1PA9m28A15mwwewFVw+gznCp
    nVvFl4MgG3YSHthpzIBoI4U4mSvk8swjEdkwS/XnrLBKz+d1QVv11l9EYtTQUNDz
    bGVvQ6Gsj+FLE453SS3W6f1dzK6e/ZKgKLtKMepqDO76ttZRa1ssAw2fdf2qCk9E
    dHy/hUFlUSUFGnIcJTl3W7DeZ9zUwMYNLOsvjP7kKVRK+r8uERjGR0AagJS5C5a7
    /N1dPetSohHlKLG/6sZkTY+kxVqwAWODAWzCi5QsC4Jiv92ayeNeINh3twiS/E5c
    6YEWaXSL7iNY2v2Q1ylVI06V6TjcJQc2yLCvE2ls
    -----END CERTIFICATE-----
