---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: alertmanager-healthchecks-io-watchdog-url
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend-platform
    kind: ClusterSecretStore
  target:
    name: healthchecks-io-watchdog-url
    creationPolicy: Owner
  data:
    - remoteRef:
        conversionStrategy: Default
        key: /victoria-metrics-stack/alertmanager/home-assistant-healthchecks-io
        property: url
      secretKey: url
