---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: oauth2-proxy-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend-platform
    kind: ClusterSecretStore
  target:
    name: oauth2-proxy-secrets
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        client-id: oauth2-proxy
        client-secret: "{{ .clientSecret }}"
        cookie-secret: "{{ .cookieSecret }}"
  data:
    - remoteRef:
        conversionStrategy: Default
        key: authentik/oauth2-clients/oauth2-proxy
        property: client-secret
      secretKey: clientSecret
      sourceRef:
        storeRef:
          name: vault-backend-homelab-platform
          kind: ClusterSecretStore
    - remoteRef:
        conversionStrategy: Default
        key: /oauth2-proxy/cookie-config
        property: cookie-secret
      secretKey: cookieSecret
