# yaml-language-server: $schema=https://raw.githubusercontent.com/argoproj/argo-workflows/master/api/jsonschema/schema.json
---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: set-key-permissions
spec:
  entrypoint: set-key-permissions
  serviceAccountName: storage-workflows
  securityContext:
    runAsGroup: 1000
    runAsUser: 100
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  activeDeadlineSeconds: 1200
  arguments:
    parameters:
      - name: bucket-name
        description: Name of the bucket to create
      - name: key
        description: Name of the key to set permissions for
      - name: read
        description: Should the key have read permissions
        enum:
          - "deny"
          - "allow"
        default: "deny"
      - name: write
        description: Should the key have write permissions
        enum:
          - "deny"
          - "allow"
        default: "deny"
      - name: owner
        description: Should the key have owner permissions
        enum:
          - "deny"
          - "allow"
        default: "deny"
  podGC:
    strategy: OnPodCompletion
  templates:
    - name: set-key-permissions
      inputs:
        parameters:
          - name: bucket-name
          - name: key
          - name: read
          - name: write
          - name: owner
      container:
        image: ghcr.io/wittdennis/devops-tools:1.2.24 # renovate
        command: [sh, -c]
        args:
          - |
            set -eu

            ALLOW_ARGS=""
            if [ "{{ inputs.parameters.read }}" = "allow" ]; then
              ALLOW_ARGS="${ALLOW_ARGS} --read"
            fi

            if [ "{{ inputs.parameters.write }}" = "allow" ]; then
              ALLOW_ARGS="${ALLOW_ARGS} --write"
            fi

            if [ "{{ inputs.parameters.owner }}" = "allow" ]; then
              ALLOW_ARGS="${ALLOW_ARGS} --owner"
            fi

            DENY_ARGS=""
            if [ "{{ inputs.parameters.read }}" = "deny" ]; then
              DENY_ARGS="${DENY_ARGS} --read"
            fi

            if [ "{{ inputs.parameters.write }}" = "deny" ]; then
              DENY_ARGS="${DENY_ARGS} --write"
            fi

            if [ "{{ inputs.parameters.owner }}" = "deny" ]; then
              DENY_ARGS="${DENY_ARGS} --owner"
            fi

            kubectl exec --stdin --tty homelab-garage-0 -- ./garage bucket allow ${ALLOW_ARGS} {{ inputs.parameters.bucket-name }} --key {{ inputs.parameters.key }}
            kubectl exec --stdin --tty homelab-garage-0 -- ./garage bucket deny ${DENY_ARGS} {{ inputs.parameters.bucket-name }} --key {{ inputs.parameters.key }}
        volumeMounts:
          - name: tmp
            mountPath: /tmp
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          capabilities:
            drop:
              - ALL
      volumes:
        - name: tmp
          emptyDir: {}
