---
apiVersion: v1
kind: Service
metadata:
  name: renovate-operator-api-homelab
  annotations:
    traefik.ingress.kubernetes.io/service.serversscheme: http
    traefik.ingress.kubernetes.io/service.passhostheader: "false"
spec:
  type: ExternalName
  externalName: api-renovate.tailnet.derwitt.net
  ports:
    - name: http
      port: 8082
      protocol: TCP
