---
apiVersion: v1
kind: Service
metadata:
  name: renovate-operator-api-homelab
  annotations:
    traefik.ingress.kubernetes.io/service.serversscheme: https
spec:
  type: ExternalName
  externalName: api.renovate.derwitt.site
