---
apiVersion: v1
kind: Service
metadata:
  name: renovate-operator-homelab
  annotations:
    traefik.ingress.kubernetes.io/service.serversscheme: https
    traefik.ingress.kubernetes.io/service.passhostheader: "false"
spec:
  type: ExternalName
  externalName: renovate.derwitt.site
  ports:
    - name: https
      port: 443
      protocol: TCP
