---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-code-and-quest-de-api-token
  namespace: cert-manager
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend-platform
    kind: ClusterSecretStore
  target:
    name: cloudflare-code-and-quest-de-api-token
    creationPolicy: Owner
  data:
    - remoteRef:
        conversionStrategy: Default
        key: /cert-manager/cloudflare-code-and-quest-de
        property: api-token
      secretKey: api-token
