---
apiVersion: v1
kind: ConfigMap
metadata:
  name: renovate-config
data:
  config.json: |-

    {
       "$schema": "https://docs.renovatebot.com/renovate-global-schema.json",
       "autodiscover": true,
       "platform": "github",
       "autodiscoverNamespaces": ["wittdennis"],
       "cacheDir": "/renovate-cache",
       "forkProcessing": "enabled",
       "detectHostRulesFromEnv": true
     }
