---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: admin-credentials
spec:
  refreshInterval: "1h0m0s"
  secretStoreRef:
    name: vault-backend-platform
    kind: ClusterSecretStore
  target:
    name: admin-credentials
    creationPolicy: Owner
    deletionPolicy: Delete
  data:
    - remoteRef:
        conversionStrategy: Default
        key: storage/admin-credentials
        property: access-key
      secretKey: access-key
    - remoteRef:
        conversionStrategy: Default
        key: storage/admin-credentials
        property: secret-key
      secretKey: secret-key
