---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: foundry-saltysausage-access-key
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend-platform
    kind: ClusterSecretStore
  target:
    name: foundry-saltysausage-access-key
    creationPolicy: Owner
    deletionPolicy: Delete
  data:
    - remoteRef:
        conversionStrategy: Default
        key: /storage/foundry-saltysausage
        property: access-key
      secretKey: access-key
    - remoteRef:
        conversionStrategy: Default
        key: /storage/foundry-saltysausage
        property: secret-key
      secretKey: secret-key
