---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dex-secrets
  namespace: dex
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend-platform
    kind: ClusterSecretStore
  target:
    name: dex-secrets
    creationPolicy: Owner
    deletionPolicy: Delete
  data:
    - remoteRef:
        conversionStrategy: Default
        key: /dex/microsoft-oidc
        property: application-id
      secretKey: microsoft-application-id
    - remoteRef:
        conversionStrategy: Default
        key: /dex/microsoft-oidc
        property: client-secret
      secretKey: microsoft-client-secret
    - remoteRef:
        conversionStrategy: Default
        key: /dex/microsoft-oidc
        property: tenant-id
      secretKey: microsoft-tenant-id
    - remoteRef:
        conversionStrategy: Default
        key: /dex/kubelogin-static-client
        property: client-secret
      secretKey: kubelogin-client-secret
    - remoteRef:
        conversionStrategy: Default
        key: /dex/argo-workflows-static-client
        property: client-secret
      secretKey: argo-workflows-sso-client-secret
