---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mogenius-operator-valkey-credentials
spec:
  refreshInterval: "1h0m0s"
  secretStoreRef:
    name: vault-backend-home-assistant
    kind: ClusterSecretStore
  target:
    name: mogenius-operator-valkey-credentials
    creationPolicy: Owner
    deletionPolicy: Delete
  data:
    - remoteRef:
        conversionStrategy: Default
        key: /mogenius-operator/valkey/credentials
        property: default-password
      secretKey: default-password
    - remoteRef:
        conversionStrategy: Default
        key: /mogenius-operator/valkey/credentials
        property: replication-password
      secretKey: replication-password
