---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mogenius-operator-api-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend-home-assistant
    kind: ClusterSecretStore
  target:
    name: mogenius-operator-api-secret
    creationPolicy: Owner
    deletionPolicy: Delete
  data:
    - remoteRef:
        conversionStrategy: Default
        key: /mogenius-operator/api-key
        property: api-key
      secretKey: api-key
