---
apiVersion: renovate-operator.mogenius.com/v1alpha1
kind: RenovateJob
metadata:
  name: forgejo-containers
spec:
  templateRef:
    name: forgejo-default
  discoveryFilters:
    - "containers/**"
