---
apiVersion: v1
kind: Secret
metadata:
  name: additional-scrape-configs
stringData:
  additional.yaml: |
    - job_name: "homelab"
      http_sd_configs:
        - url: https://netbox.derwitt.site/api/plugins/prometheus-sd/devices/?tag=node-exporter&role__n=forgejo-runner&tenant=home&status=active&has_primary_ip=true
          authorization:
            type: Bearer
            credentials_file: /netbox/api-token
        - url: https://netbox.derwitt.site/api/plugins/prometheus-sd/virtual-machines/?tag=node-exporter&role__n=forgejo-runner&tenant=home&status=active&has_primary_ip=true
          authorization:
            type: Bearer
            credentials_file: /netbox/api-token
      relabel_configs:
        - source_labels: [__address__]
          target_label: instance
        - source_labels: [__meta_netbox_primary_ip4]
          regex: '(.+)'
          target_label: __address__
        # - source_labels: [__meta_netbox_primary_ip6]
        #   regex: '(.+)'
        #   target_label: __address__
        #   replacement: '[${1}]'
        - source_labels: [__address__]
          target_label: __address__
          replacement: '${1}:9100'
    - job_name: "wireguard-server"
      http_sd_configs:
        - url: https://netbox.derwitt.site/api/plugins/prometheus-sd/virtual-machines/?name=bastion-wireguard&tag=node-exporter&tenant=personal-cloud&status=active&has_primary_ip=true
          authorization:
            type: Bearer
            credentials_file: /netbox/api-token
      relabel_configs:
        - source_labels: [__address__]
          target_label: instance
        - source_labels: [__meta_netbox_primary_ip4]
          regex: '(.+)'
          target_label: __address__
        # - source_labels: [__meta_netbox_primary_ip6]
        #   regex: '(.+)'
        #   target_label: __address__
        #   replacement: '[${1}]'
        - source_labels: [__address__]
          target_label: __address__
          replacement: '${1}:9100'
    - job_name: "parents"
      http_sd_configs:
        - url: https://netbox.derwitt.site/api/plugins/prometheus-sd/devices/?tag=node-exporter&tenant=parents&status=active&has_primary_ip=true
          authorization:
            type: Bearer
            credentials_file: /netbox/api-token
        - url: https://netbox.derwitt.site/api/plugins/prometheus-sd/virtual-machines/?tag=node-exporter&tenant=parents&status=active&has_primary_ip=true
          authorization:
            type: Bearer
            credentials_file: /netbox/api-token
      relabel_configs:
        - source_labels: [__address__]
          target_label: instance
        - source_labels: [__meta_netbox_primary_ip4]
          regex: '(.+)'
          target_label: __address__
        # - source_labels: [__meta_netbox_primary_ip6]
        #   regex: '(.+)'
        #   target_label: __address__
        #   replacement: '[${1}]'
        - source_labels: [__address__]
          target_label: __address__
          replacement: '${1}:9100'
