---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: atlantis-environment
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend-platform
    kind: ClusterSecretStore
  target:
    name: atlantis-environment
    creationPolicy: Owner
    deletionPolicy: Delete
  dataFrom:
    - extract:
        key: atlantis/environment
        property: json
