---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: semaphore
spec:
  endpoints:
    - dnsName: semaphore.derwitt.site
      recordTTL: 60
      recordType: A
      targets:
        - 100.64.0.12
    - dnsName: semaphore.derwitt.site
      recordTTL: 60
      recordType: AAAA
      targets:
        - fd7a:115c:a1e0::c
