---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vault-backup-settings
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend-platform
    kind: ClusterSecretStore
  target:
    name: vault-backup-settings
    creationPolicy: Owner
    deletionPolicy: Delete
  data:
    - remoteRef:
        conversionStrategy: Default
        key: shared/hetzner-backup-bucket-credentials
        property: access-key
      secretKey: access-key
    - remoteRef:
        conversionStrategy: Default
        key: shared/hetzner-backup-bucket-credentials
        property: secret-key
      secretKey: secret-key
    - remoteRef:
        conversionStrategy: Default
        key: /backups/vault-restic-settings
        property: restic-password
      secretKey: restic-password
