---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: netbox-passwords-seed
spec:
  refreshInterval: "1h0m0s"
  secretStoreRef:
    name: vault-backend-platform
    kind: ClusterSecretStore
  target:
    name: netbox-passwords-seed
    creationPolicy: Owner
    deletionPolicy: Delete
  data:
    - remoteRef:
        conversionStrategy: Default
        key: /netbox/passwords-seed
        property: seed
      secretKey: secret_key
