---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: netbox-oidc-credentials
spec:
  refreshInterval: "1h0m0s"
  secretStoreRef:
    name: vault-backend-platform
    kind: ClusterSecretStore
  target:
    name: netbox-oidc-credentials
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      engineVersion: v2
      mergePolicy: Replace
      data:
        oidc-credentials.yaml: |
          SOCIAL_AUTH_OIDC_SECRET: "{{ .clientSecret }}"
  data:
    - remoteRef:
        conversionStrategy: Default
        key: netbox/oidc-credentials
        property: client-secret
      secretKey: clientSecret
