---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: netbox-superuser-credentials
spec:
  refreshInterval: "1h0m0s"
  secretStoreRef:
    name: vault-backend-platform
    kind: ClusterSecretStore
  target:
    name: netbox-superuser-credentials
    creationPolicy: Owner
    deletionPolicy: Delete
  data:
    - remoteRef:
        conversionStrategy: Default
        key: /netbox/superuser-credentials
        property: username
      secretKey: username
    - remoteRef:
        conversionStrategy: Default
        key: /netbox/superuser-credentials
        property: email
      secretKey: email
    - remoteRef:
        conversionStrategy: Default
        key: /netbox/superuser-credentials
        property: password
      secretKey: password
    - remoteRef:
        conversionStrategy: Default
        key: /netbox/superuser-credentials
        property: api-token
      secretKey: api_token
