---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: netbox-valkey-credentials
spec:
  refreshInterval: "1h0m0s"
  secretStoreRef:
    name: vault-backend-platform
    kind: ClusterSecretStore
  target:
    name: netbox-valkey-credentials
    creationPolicy: Owner
    deletionPolicy: Delete
  data:
    - remoteRef:
        conversionStrategy: Default
        key: /netbox/valkey-credentials
        property: default-password
      secretKey: default-password
    - remoteRef:
        conversionStrategy: Default
        key: /netbox/valkey-credentials
        property: replication-password
      secretKey: replication-password
    - remoteRef:
        conversionStrategy: Default
        key: /netbox/valkey-credentials
        property: tasks-password
      secretKey: tasks-password
    - remoteRef:
        conversionStrategy: Default
        key: /netbox/valkey-credentials
        property: cache-password
      secretKey: cache-password
