---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: netbox-email-credentials
spec:
  refreshInterval: "1h0m0s"
  secretStoreRef:
    name: vault-backend-platform
    kind: ClusterSecretStore
  target:
    name: netbox-email-credentials
    creationPolicy: Owner
    deletionPolicy: Delete
  data:
    - remoteRef:
        conversionStrategy: Default
        key: /netbox/email-credentials
        property: password
      secretKey: email-password
